# The 'server' keyword opens a configuration block defining a virtual server (website setup).
server {
    # ACTIVE: Tells Nginx to monitor Port 80, the universal standard port for HTTP traffic.
    listen 80;
    
    # ACTIVE: Specifies the domain name this block responds to (localhost for local dev).
    server_name localhost;

    # ACTIVE: Matches any generic URL path (like the home page or static assets).
    location / {
        # ACTIVE: Maps the web request to a physical folder directory inside the container.
        root /usr/share/nginx/html;
        
        # ACTIVE: Defines the default file to open if the user doesn't type a specific filename.
        index index.html;
    }

    # ACTIVE: Catches any request path starting with /api/ (like /api/quote) to process it separately.
    location /api/ {
	
		# DNS server IP; to resolve
		#resolver 10.96.0.10 valid=30s;
		# resolver 127.0.0.11 valid=30s;
		resolver 10.100.0.10 valid=30s;
		
		# We use variable so that Nginx reads the config, sees a variable name ($backend_upstream), and says: "This destination is dynamic. I don't know what it will be until a user makes a request, so I will skip the startup check." This lets Nginx boot up successfully without panicking.
		set $backend_upstream reflection-backend-service.default.svc.cluster.local:3000;
		# set $backend_upstream backend:3000;
		
        # ACTIVE: Hands the request over to the Node container name and port over the network.
        proxy_pass http://$backend_upstream$request_uri;
        
        # OPTIMIZATION (ACTIVE): Forces Nginx to use HTTP/1.1 to keep network connections alive.
        # Nginx actively does this, but our app only fetches one quote at a time, so we don't heavily utilize this speed boost yet.
        proxy_http_version 1.1;
        
        # FUTURE PROOFING (UNUSED FOR NOW): Dynamic variable checking if the browser wants WebSockets.
        # Since our quote button uses standard HTTP, this variable evaluates to BLANK right now.
        proxy_set_header Upgrade $http_upgrade;
        
        # FUTURE PROOFING (UNUSED FOR NOW): Companion to the Upgrade line to confirm protocol switching.
        # Node.js ignores this hardcoded value because the accompanying Upgrade value above is blank.
        proxy_set_header Connection 'upgrade';
        
        # TRACKING (UNUSED FOR NOW): Forwards the original domain name (localhost) to the backend.
        # Our current server.js doesn't read or care about the domain name, so it's not utilized.
        proxy_set_header Host $host;
        
        # REDUNDANT (DEAD CODE FOR NOW): Switch to force Nginx to skip its cache if $http_upgrade has text.
        # Since we haven't configured a caching folder anywhere in this file, there is no cache to bypass.
        proxy_cache_bypass $http_upgrade;
    }
}