apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: dynamic-dev-cluster
  region: ap-south-1

managedNodeGroups:
  - name: standard-workers
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    volumeSize: 20
    privateNetworking: false